name: Mirror to GitLab

on:
  push:
    branches:
      - '**' # Triggers on all branch pushes
    tags:
      - '*' # Triggers on all tag pushes

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Push to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/bh-sfdev/global-tech-solutions.git
          
          git push gitlab --all --force
          git push gitlab --tags --force

